version: '3.8'
services:

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - comment


  user-database:
    container_name: user-database
    image: postgres:15.2
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: rasitesdmr
      POSTGRES_PASSWORD: rasitesdmr
      POSTGRES_DB: hb-db
    networks:
      - comment

networks:
  comment:
    driver: bridge